name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure CLI
        run: az login --service-principal -u ${{ secrets.AZURE_USERNAME }} -p '${{ secrets.AZURE_PASSWORD }}' --tenant '${{ secrets.AZURE_TENANT_ID }}'

      - name: Log in to Azure Container Registry
        run: az acr login --name acrotsdev

      - name: Build Docker image
        run: docker build -t acrotsdev.azurecr.io/pingtestapp2:latest .

      - name: Push Docker image to ACR
        run: docker push acrotsdev.azurecr.io/pingtestapp2:latest
